export const siteConfig = {
  businessName: "MJ-TH Express",
  businessFullName: "MJ-TH Express รถรับจ้างบางแค",
  phone: "095-583-0371",
  phoneHref: "tel:0955830371",
  lineId: "edokmzaza",
  lineUrl: "https://line.me/ti/p/_Wou4xwYjZ",
  facebookUrl: "https://www.facebook.com/people/%E0%B8%A3%E0%B8%B1%E0%B8%9A%E0%B8%88%E0%B9%89%E0%B8%B2%E0%B8%87%E0%B8%82%E0%B8%99%E0%B8%AA%E0%B9%88%E0%B8%87%E0%B8%A1%E0%B8%AD%E0%B9%84%E0%B8%8B%E0%B8%84%E0%B9%8C%E0%B8%A5%E0%B8%B1%E0%B8%9A%E0%B8%95%E0%B9%88%E0%B8%B2%E0%B8%87%E0%B8%88%E0%B8%B1%E0%B8%87%E0%B8%AB%E0%B8%A7%E0%B8%B1%E0%B8%94/61577012168287",
  baseUrl: "https://www.mj-th-express.com",
  priceRange: "฿500-฿15000",
  openingHours: "24 Hours every day",
  openingHoursTh: "เปิดบริการทุกวัน ตลอด 24 ชั่วโมง",
  address: {
    streetAddress: "85/24 ซอยอัสสัมชัญ 23 แขวงบางไผ่",
    addressLocality: "เขตบางแค",
    addressRegion: "กรุงเทพมหานคร",
    postalCode: "10160",
    addressCountry: "TH",
  },
  geo: {
    latitude: 13.7367,
    longitude: 100.3632,
  },
  serviceAreas: [
    "บางแค",
    "หนองแขม",
    "ภาษีเจริญ",
    "พุทธมณฑล",
    "ทวีวัฒนา",
    "ตลิ่งชัน",
    "บางบอน",
    "พระราม 2",
    "ฝั่งธนบุรี",
    "กรุงเทพมหานคร",
  ],
  primaryServices: [
    "รถรับจ้าง",
    "รับจ้างขนของ",
    "ย้ายบ้าน",
    "ย้ายคอนโด",
    "ส่งมอเตอร์ไซค์"
  ],
  defaultTitle: "รถรับจ้างย้ายบ้าน ขนของ ขนส่งมอเตอร์ไซค์ กระบะตู้ทึบ 4 ล้อ - MJ-TH Express",
  titleTemplate: "%s | MJ-TH Express",
  defaultDescription: "บริการรถรับจ้าง 4 ล้อตู้ทึบ ขนของ ย้ายบ้าน ย้ายหอพัก คอนโด ทั่วไทย กันฝน 100% พร้อมทีมคนยกของมืออาชีพ เริ่มต้นที่บางแค ฝั่งธนฯ ประเมินราคาฟรี โทร 095-583-0371",
  defaultOgImage: "/assets/images/best.webp",
  locale: "th_TH",
  keywords: [
    "รถรับจ้างบางแค",
    "รถรับจ้างหนองแขม",
    "รถรับจ้างพุทธมณฑล",
    "รถรับจ้างเพชรเกษม",
    "รถรับจ้างฝั่งธน",
    "รถรับจ้างพระราม 2",
    "รถรับจ้างบางบอน",
    "รถรับจ้างตลิ่งชัน",
    "รับส่งมอเตอร์ไซค์ไปต่างจังหวัด",
    "รถกระบะรับจ้างกรุงเทพ",
    "ย้ายหอพัก",
    "ย้ายบ้าน",
    "รถ 4 ล้อตู้ทึบรับจ้าง",
    "MJ-TH Express"
  ],
};

export type SiteConfig = typeof siteConfig;
